apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:   #  is important if you want your application can get the traffic from service
   x: hello  # label always be in key: value pair and it must be unique
  name: podexam  # must be unique
spec:
  containers:
  - image: nginx
    name: pod1
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: wowo2020chinmay
  name: wowo2020chinmay
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    x: hello
  type: NodePort
status:
  loadBalancer: {}
