apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    adhoc: chinmayq2
  name: adhocpod1
spec:
  containers:
  - image: nginx
    name: adhocpod1
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: q2svcchinmay
  name: q2svcchinmay
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    adhoc: chinmayq2
  type: NodePort
status:
  loadBalancer: {}
