apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: adhocrschinmay4
 labels:
  adhoc: chinmayq4

spec:
 selector:
  matchLabels:
   x: adhocrs
 replicas: 2
 template:
  metadata:
   name: mypodrs
   labels:
    x: adhocrs
  spec:
   containers:
    - name: adhocrschinmay
      image: crjain/may2020q1:v1
      ports:
       - containerPort: 80
      env:
       - name: x
         value: app1
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: q4svcchinmay
  name: q4svcchinmay
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    x: adhocrs
  type: LoadBalancer
status:
  loadBalancer: {}
